"""initial 4 models

Revision ID: 2740137cba35
Revises: 
Create Date: 2026-06-01 10:27:53.102074+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2740137cba35'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_month',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('selected_table_type', sa.String(length=32), nullable=True),
    sa.Column('selected_person_id', sa.Integer(), nullable=True),
    sa.Column('active_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_version_id'], ['schedule_version.id'], name='fk_month_active_version', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['selected_person_id'], ['schedule_person.id'], name='fk_month_selected_person', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_schedule_month_year_month')
    )
    op.create_table('schedule_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_month_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_image_path', sa.String(length=512), nullable=True),
    sa.Column('image_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_month_id'], ['schedule_month.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_month_id', 'version_number', name='uq_version_month_number')
    )
    op.create_table('schedule_person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_version_id', sa.Integer(), nullable=False),
    sa.Column('table_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_version_id'], ['schedule_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_cell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_version_id', sa.Integer(), nullable=False),
    sa.Column('schedule_person_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift_code', sa.String(length=8), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('original_ocr_value', sa.String(length=32), nullable=True),
    sa.Column('corrected_value', sa.String(length=32), nullable=True),
    sa.Column('is_user_corrected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_person_id'], ['schedule_person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_version_id'], ['schedule_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_version_id', 'schedule_person_id', 'date', name='uq_cell_version_person_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_cell')
    op.drop_table('schedule_person')
    op.drop_table('schedule_version')
    op.drop_table('schedule_month')
    # ### end Alembic commands ###
