"""스케줄 버전 모델 정제: version_number 제거, updated_at 추가

Revision ID: 1d4b705f4843
Revises: 2740137cba35
Create Date: 2026-06-03 06:32:19.403254+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d4b705f4843'
down_revision: Union[str, None] = '2740137cba35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_month_active_version', 'schedule_month', 'schedule_version', ['active_version_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_month_selected_person', 'schedule_month', 'schedule_person', ['selected_person_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('schedule_version', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('uq_version_month_number'), 'schedule_version', type_='unique')
    op.drop_column('schedule_version', 'image_deleted_at')
    op.drop_column('schedule_version', 'version_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_version', sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('schedule_version', sa.Column('image_deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_version_month_number'), 'schedule_version', ['schedule_month_id', 'version_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('schedule_version', 'updated_at')
    op.drop_constraint('fk_month_selected_person', 'schedule_month', type_='foreignkey')
    op.drop_constraint('fk_month_active_version', 'schedule_month', type_='foreignkey')
    # ### end Alembic commands ###
