"""ocr_correction table

Revision ID: f0ff87f4712c
Revises: 1d4b705f4843
Create Date: 2026-06-18 09:17:37.755878+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ff87f4712c'
down_revision: Union[str, None] = '1d4b705f4843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_correction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('original_code', sa.String(length=32), nullable=True),
    sa.Column('original_confidence', sa.Float(), nullable=True),
    sa.Column('corrected_code', sa.String(length=32), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('bbox_x', sa.Integer(), nullable=True),
    sa.Column('bbox_y', sa.Integer(), nullable=True),
    sa.Column('bbox_width', sa.Integer(), nullable=True),
    sa.Column('bbox_height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocr_correction')
    # ### end Alembic commands ###
